### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by l0oky** [Rsgm/Hakd#9]
Crashed when the application is trying to "login" or when the console was outputting "Starting Jython."

>BTW Very nice idea for the game. Will I be able to sell my scripts in store (in game) ? Reminds me of the game Dark Signs, also a hacking game, which the original author closed. It also had It's own scripting engine and a store where you can sell your scripts to others..

**Comment by Rsgm** [comment]
I really want to work on this again it is so fun writing, but I am pretty busy at the moment.

Anyway, the intro screen or 'login' was removed because of this bug. It shouldn't be in the latest version. I should take out the versions that have crashes(all of them?). Let me know what version you used, and if the current version works(it should).

Alternatively, [run the game from the source.](https://github.com/Rsgm/Hakd#building-and-running)

That is a great idea, thanks. Yeah, there will be a store for everything, probably scripts as well.
I think I will work on this some more soon.
